### ISSUE TITLE
My people section disappeared...

### ISSUE THREAD

**Issue by lampholder** [vector-im/element-x-ios#1663] opened 2023-09-08 16:16 UTC
### Steps to reproduce

...and [Element web folks think that EX nightly is the more likley culprit for mangling `m.direct` in my account data](https://github.com/vector-im/element-meta/issues/2035#issuecomment-1708488900).

I think the same thing happened to Amandine.

Basically, all my DMs got unflagged as DMs, probably by something vaping my `m.direct` in account data. This is a pretty bad failure, since it also messes with notifs (depending on default notif settings).

### Your phone model

iPhone 12 Pro

### Operating system version

16.6

### Application version

1.2.9

### Homeserver

lant.uk

### Will you send logs?

Yes

**Comment by giomfo** [comment] 2023-09-14 08:42
I got this issue too - don't know when this m.direct has been reset
I sent logs from EX v1.2.8(371)

**Comment by kegsay** [comment] 2023-09-14 09:04
I'm guessing the client doesn't fetch the DM account data event before setting it? If it just relies on /sync to return the DM account data event then it could miss it if there are sync issues like the token stuff we've been seeing, or numerous other intermittent problems.

**Comment by giomfo** [comment] 2023-09-14 10:03
FYI I think I triggered this issue on my account by accepting recently new DM invites from EX iOS

To reproduce (not sure) :
- log in an existing account with more than 100 DMs in EX iOS
- close/stop the app
- send a new DM invite to this account
- open EX iOS and accept the pending invite

**Comment by poljar** [comment] 2023-09-15 10:51
Rust PR attempting to fix this: https://github.com/matrix-org/matrix-rust-sdk/pull/2553.

**Comment by manuroe** [comment] 2023-09-19 07:32
Should be fixed in 1.2.9 release with the mentioned SDK bugfix mentioned above. Reopen if it is not the case.

**Comment by gaelledel** [comment] 2023-11-13 11:51
I have a similar issue on Element Web & Desktop. All my DMs are absent from all my People lists. I used to have hundreds of DMs. 
Now,  only the people I restarted a conversation with recently are present and show avatars (x2). All other DMs have their avatars missing and I have to search for them in order to access the DM. (Everything is up to date and issue is present both on web and desktop) 
Element version: 781a06777291-react-6ee8349f7ce6-js-d179b8c557ee
Crypto version: Olm 3.2.15
<img width="414" alt="Screenshot 2023-11-13 at 12 38 08" src="https://github.com/vector-im/element-x-ios/assets/76945183/b55ce9bc-ef38-4310-b9ec-062c95200eb8">

**Comment by giomfo** [comment] 2023-11-14 08:48
@gaelledel Did you accept an invite to a new DM on EX-iOS version **<** 1.2.9?
If this is the case, most of your DM rooms have been probably removed from the DM dictionary by mistake when the new DM has been added. When this happened, this impacted your account data, so your DMs have disappeared from all your Element clients (web, mobile...).
If you want to restore some of your DMs, the only way I know is to manually turn on the toggle "Direct Chat" of the room settings in the Legacy Element-iOS client: 
<img width="386" alt="image" src="https://github.com/vector-im/element-x-ios/assets/8969772/ba3c39dd-d743-4285-8f04-ab995ad9c851">

I think we should close this issue, the root cause has been fixed since EX v1.2.9

**Comment by gaelledel** [comment] 2023-11-14 11:53
@giomfo Thank you for your suggestions! I am unsure if the version was the following EX-iOS version < 1.2.9 but I will try your fix.

**Closed by gaelledel** 2023-11-14 11:53 UTC
Labels: X-Needs-Rust, T-Defect, S-Major, O-Occasional, Z-Schedule
