### ISSUE TITLE
Date markers appear before every single timeline entry

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1336] opened 2023-07-16 13:23 UTC
### Steps to reproduce

![IMG_0861](https://github.com/vector-im/element-x-ios/assets/1294269/e0236e5e-d220-4ac1-b833-0ae20190e5e4)

#### What did you expect?

date markers in the right place

#### What happened instead?

date markers everywhere.

my rageshakes today should include logs for this

### Application version

291

### Will you send logs?

Yes

**Comment by ara4n** [comment] 2023-07-23 11:16
see #1380 of a video of it happening

**Comment by Hywan** [comment] 2023-08-21 13:04
I'm not able to reproduce it. Is it fixed? Is anyone able to reproduce it again? cc @ara4n

**Comment by Hywan** [comment] 2023-08-21 13:22
I'm closing the issue in case it goes in the limbo. Feel free to re-open if someone sees the bug again.

**Comment by stefanceriu** [comment] 2023-08-24 10:13
![Screenshot 2023-08-24 at 13 06 17](https://github.com/vector-im/element-x-ios/assets/637564/17f1693f-68a9-4e16-9e19-9f018cbedc41)

I randomly saw it today in one of my test rooms. Wouldn't be able to tell you why it showed up

**Comment by Hywan** [comment] 2023-08-24 10:20
Did you send a rageshake?

**Comment by stefanceriu** [comment] 2023-08-25 07:10
Unfortunately not and I can't reproduce it anymore

**Comment by ara4n** [comment] 2023-08-27 10:02
i have this reliably every time i post a message into a room for the first time that day. i just rageshaked on one.

**Comment by ara4n** [comment] 2023-08-27 10:05
repro'd it again on another room; here's the video:

https://github.com/vector-im/element-x-ios/assets/1294269/6a974b3a-80ee-4be7-afd1-5def8a757a6d

**Comment by Hywan** [comment] 2023-08-28 08:06
It appears to happen when the timeline is loaded from the cache.

**Closed** 2023-09-14 12:14 UTC
Labels: X-Needs-Rust, A-Timeline, T-Defect, S-Major, O-Uncommon, Z-Schedule, Z-Polish
