### ISSUE TITLE
DM and user color are different

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-x-ios#1877] opened 2023-10-11 10:48 UTC
### Steps to reproduce

1. i have a DM with a user that has no avatar set
2. the DM's name and avatar is usually interpolated based on that other user's name and avatar
3. since none is set, the interpolation should use the placeholder avatar (=color)

#### What did you expect?
on web (and all other DMs I can find), the colors of DMs match those of the "other" participant. That includes "DMs" with more than 2 participants, that joined after the "primary" other participant.
#### What happened instead?
the DM avatar placeholder is purple, but the user's placeholder and displayname color is green

### Your phone model

12

### Operating system version

17.0.3

### Application version

1.3.2

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by pixlwave** [comment] 2023-10-11 13:45
Duplicate of #1659.

**Closed by pixlwave** 2023-10-11 13:45 UTC
Labels: T-Defect
