### ISSUE TITLE
Static location sharing

### ISSUE THREAD

**Issue by stefanceriu** [vector-im/element-x-ios#256] opened 2022-10-25 07:17 UTC
Add support for static location sharing similar to Element

- \[ \] Selecting and sending static current location
- \[ \] Displaying location in the timeline
- \[ \] Viewing received location

**Comment by kittykat** [comment] 2023-07-12 09:27
Duplicate of vector-im/element-meta/issues/1525

**Closed by kittykat** 2023-07-12 09:27 UTC
Labels: Z-BBQ-Beta, Team: ?
