### ISSUE TITLE
Long replies don't clip any more

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#2137] opened 2023-11-21 22:39 UTC
### Steps to reproduce

1. Reply to a message
2. Write a long reply
3. The reply overflows the composer area and sprawls up over the reply text:

![image](https://github.com/vector-im/element-x-ios/assets/1294269/d49e62e4-c892-44fa-b011-8a1819a17bb0)

#### What did you expect?

Clippage

#### What happened instead?

Overflowage

### Your phone model

iPhone 12 Pro Max

### Operating system version

iOS16.4

### Application version

1.4.2 (440)

### Will you send logs?

No

**Comment by stefanceriu** [comment] 2023-11-22 07:40
Duplicate of #1832

**Closed by stefanceriu** 2023-11-22 07:40 UTC
Labels: T-Defect
