### ISSUE TITLE
App got completely stuck sending messages

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1353] opened 2023-07-18 12:28 UTC
### Steps to reproduce

I've had two instances today of trying to send messages into (different) rooms, where sending got completely wedged.

Looks like the E2EE sync loop is getting stuck somehow, perhaps calling /keys/query on a device whose server is down, or a bug in rust-sdk-crypto grinding to a halt.

#### What did you expect?

E2EE that works, and messages whose sending don't get stuck solid.

#### What happened instead?

Stuck send msgs, which i can't recover from.

### Application version

292

### Will you send logs?

Yes

**Comment by bnjbvr** [comment] 2023-07-20 09:28
Looking.

**Comment by bnjbvr** [comment] 2023-07-28 12:37
4/6 of the above crash reports include the following panic in Rust code:

```
2023-07-27_161951-ZBIH5VQT/console.3_1.log
258:thread 'tokio-runtime-worker' panicked at 'Session wasn't created nor shared', /Users/mauroromito/Documents/Xworkspace/matrix-rust-sdk/crates/matrix-sdk-crypto/src/session_manager/group_sessions.rs:205:50
260:2023-07-27T00:07:33.309181Z ERROR root:send_queued_messages{room_id="XXX:matrix.org"}: matrix_sdk_ui::timeline::queue: crates/matrix-sdk-ui/src/timeline/queue.rs:144: Message-sending task failed: task 283504 panicked
```

This seems to match the symptoms (not being able to send messages). @poljar and I debugged this, and we think it's caused by a combination of two issues:

- on the one hand, when the olm machine is getting regenerated because it detected some other apps took the cross-process lock, it will invalidate its internal caches. Assuming a perfect timing of events, this could in theory happen in the middle of sending messages (between sharing a room key *and* encrypting a message with that room key), leading to a bad race condition. The encryption not seeing the cached room key data would assume invalid state and panic; this will get fixed with https://github.com/matrix-org/matrix-rust-sdk/pull/2348
- on the other hand, the olm machine gets invalidated way more than it should (i.e. every time we attempt to take the lock), and this is getting fixed in https://github.com/matrix-org/matrix-rust-sdk/pull/2347.

My hope is that, despite the panic not appearing in the two other rageshakes, this is the same issue, or that the second PR will make it a non-issue.

Assuming the fixes go in quickly today, we can consider whether to close this issue in a week or so, if there are no new instances of this problem after the fix is in.

**Comment by bnjbvr** [comment] 2023-08-05 10:06
I claim this has been fixed by the two PRs mentioned in the previous comment. If new issues appear, we can fix them later.

**Closed by bnjbvr** 2023-08-05 10:06 UTC
Labels: X-Needs-Rust, T-Defect, A-E2EE, S-Critical, O-Uncommon, Z-Schedule
