### ISSUE TITLE
Voice message recording: "Lock" (slide up) not working

### ISSUE THREAD

**Issue by jacotec** [vector-im/element-x-ios#2085] opened 2023-11-15 10:29 UTC
### Steps to reproduce

In EX the voice messages are now pretty well implemented, unfortunately there is an issue with recording. Sliding the recording icon up (like in Element-IOS, Whatsapp, Signal etc.) does not work, so the only way to record a voice messages is to keep the tiny icon pressed all the time. This makes it unusable for longer messages than a few seconds and does not work in a car at all where we need our hands during recording.

#### What did you expect?

Sliding the icon up should "lock" the recording so you don't need to press the icon all the time (behavior like in Element-IOS)

#### What happened instead?

You need to keep the icon pressed all the time which renders it unusable for longer recordings or use in the car (where voice messages are essential)

### Your phone model

iPhone 14 Pro Max

### Operating system version

IOS 17.1.1

### Application version

1.4.1

### Homeserver

Synapse 1.95.1

### Will you send logs?

No

**Comment by pixlwave** [comment] 2023-11-15 10:47
Duplicate of #2023.

**Closed by pixlwave** 2023-11-15 10:47 UTC
Labels: T-Defect
