### ISSUE TITLE
Blocks of history are going entirely missing

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1197] opened 2023-06-28 12:38 UTC
### Steps to reproduce

1. Decide you want to read a room you haven't read before on EIX
2. Filter on roomlist to find it
3. Enter it
4. See the correct most recent message in the room - and then 15 messages are missing from the timeline before older history is visible.
5. Wait a while to see if the older history turns up; it doesn't.
6. Go to room list
7. Go back into the room
8. History is now visible.

This is the second time i've seen this today.

#### What did you expect?

Reliable room history

#### What happened instead?

Big missing block of history.  Presumably /messages backwards paginating from the wrong token, or trickle /sync isn't working, or something.

### Application version

257

### Will you send logs?

Yes

**Comment by ara4n** [comment] 2023-06-28 13:31
i hit this again (although after waiting ages (35s) the history appeared without me having to go out & in to the room again)

**Comment by manuroe** [comment] 2023-07-12 09:15
We now know that is due to https://github.com/matrix-org/sliding-sync/issues/197

**Comment by manuroe** [comment] 2023-07-12 11:43
I removed " (but turn up next time you enter the room)" from the title because, with the room cache, this trick does not solve the problem anymore.

**Comment by pixlwave** [comment] 2023-07-12 11:56
Steps to reproduce:

- Open room on device B
- Send messages from device A
- Background the app on device B (keeping the room visible, haven't confirmed without that yet.)
- *Wait for the session to expire*
- Send enough messsages to trigger a limited sync from device A
- Open the app on device B

![Screenshot 2023-07-12 at 11 22 33 am](https://github.com/vector-im/element-x-ios/assets/6060466/232d482c-2492-4a52-805f-bd4188eb5ef5)

**Comment by ara4n** [comment] 2023-07-12 11:56
but the rageshakes we're seeing from jennifilm & sm are not using the cache yet?

**Comment by manuroe** [comment] 2023-07-12 12:10
The room in-memory cache is in production. It caches data of all visited rooms in the app to speed up switching between rooms.
The room list cache, the permanent cache to store the room list, is not yet enabled.

**Comment by pixlwave** [comment] 2023-07-18 10:42
Closed by https://github.com/matrix-org/matrix-rust-sdk/pull/2278

**Closed by pixlwave** 2023-07-18 10:42 UTC
Labels: A-Timeline, T-Defect, S-Critical, O-Uncommon, Z-Schedule
