### ISSUE TITLE
App crashes on block/unblocking user

### ISSUE THREAD

**Issue by germain-gg** [vector-im/element-x-ios#1998] opened 2023-10-31 19:36 UTC
- go to user details
- click block

And then the app crashes. Upon reopening the user is actually blocked. If you unblock them the same thing happens again.

**Comment by pixlwave** [comment] 2023-11-03 13:24
I'm unable to reproduce the crash following these steps on an iPhone:
- From the timeline tap a user's avatar.
- Tap Block User in the user details screen.

Or 
- From the timeline tap the room header.
- Tap the People button to get to the members list.
- Tap a member.
- Tap Block User in the user details screen.

If there's any more information you have on this, let me know and I'll try dig into it further.

**Comment by stefanceriu** [comment] 2023-11-15 12:25
I am unable to reproduce it either, closing for now.

**Closed by stefanceriu** 2023-11-15 12:25 UTC
Labels: T-Defect, X-Needs-Info, A-User-Detail, Z-Schedule
