### ISSUE TITLE
iOS backup restore breaks verification

### ISSUE THREAD

**Issue by namazso** [vector-im/element-x-ios#2169] opened 2023-11-25 11:51 UTC
### Steps to reproduce

1. Make an iTunes backup
2. Restore to another device (maybe works with same too, I didn't test)
3. Open Element X
4. Try verifying the new device
5. Verification will always say you cancelled it

Logging out and in fixes the issue

#### What did you expect?

Either no verification request, or a working one

#### What happened instead?

Broken verification

### Your phone model

iPhone 15 Pro

### Operating system version

iOS 17.1.1

### Application version

1.4.2 (79)

### Homeserver

Synapse 1.96.1

### Will you send logs?

No

**Comment by pixlwave** [comment] 2023-11-27 08:37
Duplicate of #1947

**Closed by pixlwave** 2023-11-27 08:37 UTC
Labels: T-Defect
