### ISSUE TITLE
Unread count on desktop is still there after logging out of TF

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-x-ios#898] opened 2023-05-16 08:47 UTC
### Steps to reproduce

1. Be logged into the app
2. See unread count on the desktop app icon
3. Log out of the app
4. Continue seeing the unread count on the desktop app icon:
![IMG_0241](https://github.com/vector-im/element-x-ios/assets/51663/b028123a-4401-4daf-ab24-895621e2c595)

#### What did you expect?
No red unread count shown when I am logged out. Unread count is green, not red, to match notification designs.

#### What happened instead?
Unread count continues to show after I'm logged out

### Your phone model

iPhone 11

### Operating system version

iOS 16.4.1 (a)

### Application version

TestFlight (even after today's update while logged out)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by stefanceriu** [comment] 2023-09-08 10:20
Dupe of #1573

**Closed by stefanceriu** 2023-09-08 10:20 UTC
Labels: T-Defect, S-Major, O-Uncommon, X-Maybe-Release-Blocker, Z-Schedule, Z-Retest
