### ISSUE TITLE
Ignore membership events for the last message in the room list

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#413] opened 2023-01-05 17:41 UTC
We should have the same behaviour as Element. It should improve the ordering 🤞

——-

**Solves Chronic Issue 45d | **Users expect sorting their roomlist by activity not to consider profile changes.

**Comment by pixlwave** [comment] 2023-01-06 16:48
Event types supported for the last message in EI are in [MXKAppSettings](https://github.com/vector-im/element-ios/blob/33a7c27c0bfc08e2225bb90e398eca6a85ac8407/Riot/Modules/MatrixKit/Models/MXKAppSettings.m#L188).

**Comment by manuroe** [comment] 2023-01-09 08:33
Thanks for the reference.

> Event types supported for the last message in EI are in [MXKAppSettings](https://github.com/vector-im/element-ios/blob/33a7c27c0bfc08e2225bb90e398eca6a85ac8407/Riot/Modules/MatrixKit/Models/MXKAppSettings.m#L188).

I am a bit surprised by [`kMXEventTypeStringRoomMember`](https://github.com/vector-im/element-ios/blob/33a7c27c0bfc08e2225bb90e398eca6a85ac8407/Riot/Modules/MatrixKit/Models/MXKAppSettings.m#L192) appearing in this list. There should be more filtering elsewherE.

**Comment by ara4n** [comment] 2023-05-22 15:06
@kegsay says that the sliding sync proxy should get this right these days:

> yes this is `bump_event_types`

however, empirically, it's still a horrible problem on EX. have we failed to turn it on or something?

**Comment by stefanceriu** [comment] 2023-05-22 15:34
> have we failed to turn it on or something?

We have not, no https://github.com/vector-im/element-x-ios/blob/develop/ElementX/Sources/Services/Client/ClientProxy.swift#L408

Unfortunately I wasn't able to produce good logs for when it actually doesn't work

**Comment by stefanceriu** [comment] 2023-05-23 17:06
> Unfortunately I wasn't able to produce good logs

Okay, I finally got it, no idea why I didn't make the connection before: ignoring events works just fine while the app is running, but restarting it (or ss) seems to just use the latest event anyway. 

I imagine this should be pretty easy reproduce backend side cc @DMRobertson

**Comment by DMRobertson** [comment] 2023-05-23 17:13
The proxy will use the last event timestamp for sorting rooms by recency when it serves a new sliding sync connection. I suppose we could make this work when creating a new Conn by doing a database query. Any objections to this @kegsay---I think you had concerns in this area wrt perf before?

**Comment by DMRobertson** [comment] 2023-05-24 12:02
> This is costly because we will scan backwards (from the most recent event) to find the first `m.foo` event. We have choices when to pay this cost:

Other thoughts: 
- Could we add an index for this use case? Say (room_id, event_type, timestamp?)
- Could we track the latest event of each type per-room in a separate table?

**Comment by kegsay** [comment] 2023-05-25 07:41
Having thought about this a bit more, it's worse because:

> once up front for everyone at startup. This implies each room has a new map of event type -> last event timestamp with this type, which is kept up-to-date with live traffic. This slows down startup times and increases global memory usage, but it's a flat cost and not O(n) with # conns.

we cannot have global event type -> ts maps per-room because.... history visibility. We'd leak the latest timestamps in each room. We have to put this on the user cache, which is lazily loaded at conn startup time.

**Comment by kegsay** [comment] 2023-06-01 09:23
We could make a tradeoff here and optimise the use case of `m.room.message` and `m.room.encrypted` by precaching these values globally, and then checking that the user is joined at the time those messages were sent. This would end up looking like:
```go
type EventMetadata struct {
    NID uint64
    Timestamp uint64
}

type RoomMetadata struct {
    // ...
    LatestEventsByType map[string]EventMetadata
}
```

This is kept up-to-date with live traffic once globally. When a connection wants to `bump_event_types: [m.room.message]` they pull out the `EventMetadata` to know what the NID is (and hence when it happened). If the connection remembers the join event NID, then it can just be a direct `if joinEventNID < thisNID {` aka you joined the room before this event was sent. Critically, we must be using the _latest_ join event NID else we will leak event metadata (e.g you joined the room at room creation then immediately left, your join event NID is low whilst message NIDs are high). We could potentially return the joined event NIDs at connection startup as we already pull out joined room IDs then via:
```go
func (c *GlobalCache) LoadJoinedRooms(ctx context.Context, userID string) (pos int64, joinedRooms map[string]*internal.RoomMetadata, err error) {
```

If `joinEventNID > thisNID` then we should use the timestamp of `joinEventNID` instead for sorting purposes.

This will have a number of tradeoffs:
 - History visibility is ignored, and we always use the most conservative value (`joined` in this case). This isn't technically _that_ bad, as because we use the join event timestamp as the fallback, it will likely end up providing the right UX (you join a room, it is bumped to the point you joined the room, rather than "bumping" down to an event 5 years ago if it's a dead room).
 - If you join/leave a room several times, we only use the latest value. This is an edge case of the above point, and again the UX is probably right by using the join event instead of "some event 3 hours ago from when you were last joined to the room".


I think this is probably the best trade off?

**Comment by DMRobertson** [comment] 2023-06-01 10:50
> I think this is probably the best trade off?

To summarise:

- at proxy startup, create empty in-memory maps `LatestEventsByType` for each room as above
- update those as the proxy accumulates events; make no effort to populate them at startup
- LoadJoinedRooms additionally returns the NID of your latest join, which the connection remembers
- Consult the room's `LatestEventsByType` map when looking for a recency timestamp. Clamp NIDs from below, so that they are at least those of your latest join.
- Therefore we no longer need to track activity timestamps on the RoomConnMetadata?

**Comment by stefanceriu** [comment] 2023-06-12 10:02
Fixed as of https://github.com/matrix-org/sliding-sync/pull/142 which was already deployed

**Closed by stefanceriu** 2023-06-12 10:02 UTC
Labels: Z-BBQ-Beta, A-Room-List, X-Needs-Backend
