### ISSUE TITLE
Gaps in the room list

### ISSUE THREAD

**Issue by germain-gg** [vector-im/element-x-ios#1391] opened 2023-07-24 14:15 UTC
### Steps to reproduce

Open the apps

#### What did you expect?

No gaps

#### What happened instead?

![Screenshot](https://github.com/vector-im/element-x-ios/assets/769871/f3671c93-b2a1-4cc5-97c3-1161f82559a4)

### Will you send logs?

Yes

**Comment by solarkraft** [comment] 2023-07-24 17:11
I can confirm this. It happens sometimes and the rooms sometimes briefly reappear while scrolling. Clicking the empty spots does nothing. The rooms that seem to reappear are (I think) rooms that are already displayed above.

**Comment by Velin92** [comment] 2023-07-28 10:01
Duplicate of https://github.com/vector-im/element-x-ios/issues/1157

**Closed** 2023-07-28 10:01 UTC
Labels: T-Defect
