### ISSUE TITLE
Messages sent while on bad connectivity can be entirely lost.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#675] opened 2023-03-06 17:29 UTC
### Steps to reproduce

1. Sent a message whilst on bad connectivity.
2. Wait for encryption to do its thing
3. Lose connectivity entirely before the message has sent
4. See a (!) logo on the message
5. Go to the roomlist and back into the room
6. Watch as the message flickers and disappears forever.

#### What did you expect?

Even if we don't queue msgs to be sent yet, i'd expect unsent messages never to be lost.

#### What happened instead?

My messages got lost.

### Application version

1.0.23 (42)

### Will you send logs?

No

**Comment by pixlwave** [comment] 2023-03-07 10:03
Duplicate of #517.

**Closed by pixlwave** 2023-03-07 10:03 UTC
Labels: T-Defect
