### ISSUE TITLE
Sending photos from EIX results in weird vertical padding on EW

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#980] opened 2023-05-29 14:24 UTC
I assume we're sending the wrong dimensions somehow on the thumbnail/image on the metadata sent by EIX?  Images from other clients seem to be fine:

<img width="757" alt="Screenshot 2023-05-29 at 15 19 28" src="https://github.com/vector-im/element-x-ios/assets/1294269/2ee3e5be-f8a5-45ab-a656-20005e7c22fc">

n.b. empty space above & below the image.

**Comment by ara4n** [comment] 2023-05-29 14:24
this on build 226

**Comment by stefanceriu** [comment] 2023-05-29 14:36
@ara4n Can I have some details on the image you're trying to send please? Or maybe the actual image just redacted?

**Comment by pixlwave** [comment] 2023-07-11 11:37
As we're unable to reproduce this without the specific image (and I've tried sending photos in all 4 orientations) I'm going to close the issue.

**Comment by ara4n** [comment] 2023-08-15 19:53
this is still happening as of build 343, and reproduceable 100%.

Repro steps are:
 * Send a typical 4:3 photo from iPhone into an E2EE room.
 * View photo in EW/ED
 * Observe large vertical padding on the thumbnail in EW/ED:

<img width="735" alt="Screenshot 2023-08-15 at 20 48 30" src="https://github.com/vector-im/element-x-ios/assets/1294269/c2d91f8f-f6d0-4da8-98c5-bd95d9dcede4">

The JSON for this example is:

```json
{
  "content": {
    "body": "IMG_2532.jpeg",
    "file": {
      "hashes": {
        "sha256": "SDlmec/9JNWTYDIsYxu4o+/iq1ZhzenszQFXu9DCmOU"
      },
      "iv": "...",
      "key": {
        "alg": "A256CTR",
        "ext": true,
        "k": "...",
        "key_ops": [
          "encrypt",
          "decrypt"
        ],
        "kty": "oct"
      },
      "url": "mxc://matrix.org/opjIypnflUZgNczkTyldLtqh",
      "v": "v2"
    },
    "info": {
      "h": 3024,
      "mimetype": "image/jpeg",
      "size": 1761931,
      "thumbnail_file": {
        "hashes": {
          "sha256": "brwoRZNalwQMdj/u/Y4xKJM/Bc9N/3MF6SDcdrH/Q+Q"
        },
        "iv": "...",
        "key": {
          "alg": "A256CTR",
          "ext": true,
          "k": "...",
          "key_ops": [
            "encrypt",
            "decrypt"
          ],
          "kty": "oct"
        },
        "url": "mxc://matrix.org/xoaazsNqXcGnVQSrzVVSvVjn",
        "v": "v2"
      },
      "thumbnail_info": {
        "h": 450,
        "mimetype": "image/jpeg",
        "size": 35015,
        "w": 600
      },
      "w": 4032,
      "xyz.amorgan.blurhash": "KlHdmV,;WC~VoJWVFxOEj["
    },
    "msgtype": "m.image"
  },
  "room_id": "!ZBAyAAUngCCBvXHRkR:matrix.org",
  "type": "m.room.message"
}
```

Meanwhile, sending precisely the same image from ED, results in this:

<img width="1063" alt="Screenshot 2023-08-15 at 20 52 37" src="https://github.com/vector-im/element-x-ios/assets/1294269/209f03d7-49c7-4990-9121-65f82fc3d79f">

(note no spurious vertical spacing).

The JSON for this one is:

```json
{
  "type": "m.room.message",
  "content": {
    "body": "IMG_2532.jpeg",
    "info": {
      "size": 1761931,
      "mimetype": "image/jpeg",
      "thumbnail_info": {
        "w": 800,
        "h": 600,
        "mimetype": "image/jpeg",
        "size": 316578
      },
      "w": 4032,
      "h": 3024,
      "xyz.amorgan.blurhash": "LlHnB4,;WCbH~VoJWVa{FxOEj[jZ",
      "thumbnail_file": {
        "v": "v2",
        "key": {
          "alg": "A256CTR",
          "ext": true,
          "k": "...",
          "key_ops": [
            "encrypt",
            "decrypt"
          ],
          "kty": "oct"
        },
        "iv": "...",
        "hashes": {
          "sha256": "BpbWTXaCV7wVxYDe8QnQaZ8edcNwZlQRZT4/7srzhIs"
        },
        "url": "mxc://matrix.org/xAWDSLhEohdzrptYnpuxAvZs"
      }
    },
    "msgtype": "m.image",
    "file": {
      "v": "v2",
      "key": {
        "alg": "A256CTR",
        "ext": true,
        "k": "...",
        "key_ops": [
          "encrypt",
          "decrypt"
        ],
        "kty": "oct"
      },
      "iv": "...",
      "hashes": {
        "sha256": "l6t8z5CW+KI8Pgr1VZ8z8k/ebcHM8tHcQ/VIkvDlLT0"
      },
      "url": "mxc://matrix.org/mYzSleHjWQnVYzbOqgCHDDvQ"
    }
  }
}
```

**Comment by ara4n** [comment] 2023-08-15 20:02
...so from a quick inspection, the only immediate difference is that the thumbnail sent by EW is 800x600 and the one by EX is 600x450 (which sounds like a thinko; i'd expect it to be 800x600 to match EX).

So I suspect this is mainly a CSS bug in EW where a 600x450 thumbnail is spuriously shown floating within an 800x600 `mx_MImageBody_thumbnail_container` (despite the container only having a max-width/height of 800x600).  However, a quick workaround (which would give better image quality!) would be to fit the thumbnail to 800x600 (good old SVGA) rather than the weird 600x450 that EIX is currently emitting.

**Comment by ara4n** [comment] 2023-08-15 20:02
for the sake of completeness, here's the precise
 image used in the examples above, although i think it's clear that any large 4:3 image will repro this:

![IMG_2532](https://github.com/vector-im/element-x-ios/assets/1294269/da0c1d62-c09e-4d80-b523-84d4f9fca0f5)

**Closed** 2023-09-01 11:58 UTC
