### ISSUE TITLE
DM shows incorrect avatar (fallback/default) in room list

### ISSUE THREAD

**Issue by germain-gg** [vector-im/element-x-ios#1419] opened 2023-07-28 10:03 UTC
### Steps to reproduce

1. I don't know

But this happens on my DM with t3chguy . And is persistent after an app restart

#### What did you expect?

To have the correct avatar in the room list for that DM

#### What happened instead?

I see the fallback avatar. If I open the room and check the room details, the avatar shows correctly.

### Will you send logs?

Yes

**Comment by Velin92** [comment] 2023-07-28 10:06
Related to https://github.com/vector-im/element-x-ios/issues/917

**Comment by kittykat** [comment] 2023-07-31 09:25
Duplicate of vector-im/element-meta#1079

**Closed by kittykat** 2023-07-31 09:25 UTC
Labels: A-Room-List, T-Defect, X-Needs-Backend, S-Minor, O-Frequent
