### ISSUE TITLE
Can´t find users from own homeserver in app, but in element web. 

### ISSUE THREAD

**Issue by NiTRoeSE** [vector-im/element-x-ios#1649] opened 2023-09-07 06:58 UTC
### Steps to reproduce

1. Try to start a new chat with a user on your home server 
2. Type in first or last name 

#### What did you expect?

Find the users or get suggestions for users on my homeserver.

#### What happened instead?

I get only suggestions for foreign users from matrix.org
Note that our home server is private and did not federate with matrix.org or any other server.

- homeserver.yml

```
user_directory:
    enabled: true
    search_all_users: true
    prefer_local_users: true

```

**On Element Web i can find the users from our home server and don't get suggestions for user from matrix.org**

Interesting : On Element X for iOS i have the same behavior.

### Your phone model

Iphone 14 Pro

### Operating system version

IOS 16.6

### Application version

1.11.1

### Homeserver

Synapse 1.91.2

### Will you send logs?

Yes

**Comment by stefanceriu** [comment] 2023-11-21 13:34
I had a go at trying to reproduce this on our side with a test homeserver disconnected from the federation, a brand new account and 2 invites from Alice and Bob:
- searching for `Alice`, the app correctly calls `https://homeserver/_matrix/client/v3/user_directory/search` with `"search_term": "Alice"` and gets back **zero** results. Same happens for Bob
- accepting the invite from Alice and implicitly being in the same room makes the call above return Alice (and only Alice) as a result
- the same results are returned in the web app when using the home server as it's using the same endpoint and parameters

Looking at the [endpoint specification](https://spec.matrix.org/latest/client-server-api/#post_matrixclientv3user_directorysearch) it seems that the homeserver implementation can indeed take certain liberties with the results, presumably for security and spam reasons.

```
The homeserver may determine which subset of users are searched, however the homeserver MUST at a minimum consider the users the requesting user shares a room with and those who reside in public rooms (known to the homeserver). The search MUST consider local users to the homeserver, and SHOULD query remote users as part of the search.
```

Now, depending on what your local topology looks like this might or might not be a homeserver bug, but it's definitely not an application one. I would suggest you redirect it to the [synapse repo](https://github.com/matrix-org/synapse).

I'm going to close this ticket for now but please do reopen if you don't agree.

**Closed by stefanceriu** 2023-11-21 13:34 UTC
Labels: T-Defect, Team: Element X Feature, A-DMs, Z-Schedule
