### ISSUE TITLE
Pasted content does not respect line breaks

### ISSUE THREAD

**Issue by germain-gg** [vector-im/element-x-ios#1418] opened 2023-07-28 09:58 UTC
### Steps to reproduce

1. Play [Wordle](https://www.nytimes.com/games/wordle/index.html)
2. Copy your results
3. Paste them in the EX composer
4. Hit send

#### What did you expect?

<img width="175" alt="Screenshot 2023-07-28 at 10 57 49" src="https://github.com/vector-im/element-x-ios/assets/769871/226d3ec3-2616-4590-a990-a3f2548fd04d">

#### What happened instead?

<img width="389" alt="Screenshot 2023-07-28 at 10 58 05" src="https://github.com/vector-im/element-x-ios/assets/769871/e6d956c0-667c-4c56-bd50-4702dfe28726">

### Will you send logs?

No

**Comment by amshakal** [comment] 2023-07-28 10:09
Happens to me as well!

**Comment by stefanceriu** [comment] 2023-08-08 10:53
I'm not sure if this is because of something we changed recently or not but it seems to be working properly now. @germain-gg or @amshakal, can you confirm please?

![Screenshot 2023-08-08 at 13 52 55](https://github.com/vector-im/element-x-ios/assets/637564/627c2d2a-4b45-4785-a31c-dd070989519e)

**Comment by germain-gg** [comment] 2023-08-08 12:57
@stefanceriu I have tested and now when pasted in the composer the content respects the line breaks, but if you hit send, it inlines each guess from your Wordle result

**Comment by bnjbvr** [comment] 2023-08-21 17:40
How is the message created?

**Comment by Hywan** [comment] 2023-08-23 12:24
So…

The following Markdown:

```
Wordle 793 4/6

⬛⬛🟨⬛⬛
🟨⬛⬛⬛⬛
🟩🟩⬛⬛⬛
🟩🟩🟩🟩🟩
```

is compiled to the following HTML:

```html
<p>Wordle 793 4/6</p>
<p>⬛⬛🟨⬛⬛
🟨⬛⬛⬛⬛
🟩🟩⬛⬛⬛
🟩🟩🟩🟩🟩</p>

```

[See what Dingus says about it](https://spec.commonmark.org/dingus/?text=Wordle%20793%204%2F6%0A%0A%E2%AC%9B%E2%AC%9B%F0%9F%9F%A8%E2%AC%9B%E2%AC%9B%0A%F0%9F%9F%A8%E2%AC%9B%E2%AC%9B%E2%AC%9B%E2%AC%9B%0A%F0%9F%9F%A9%F0%9F%9F%A9%E2%AC%9B%E2%AC%9B%E2%AC%9B%0A%F0%9F%9F%A9%F0%9F%9F%A9%F0%9F%9F%A9%F0%9F%9F%A9%F0%9F%9F%A9).

And that's exactly what the Rust SDK provides.

All the messages Element X sends are formatted to Markdown, see [the sending part](https://github.com/vector-im/element-x-ios/blob/beeb5fc83c5af66fbea451afe61d2b8b40302d43/ElementX/Sources/Services/Room/RoomProxy.swift#L254), and the [formatting of the message](https://github.com/vector-im/element-x-ios/blob/beeb5fc83c5af66fbea451afe61d2b8b40302d43/ElementX/Sources/Services/Room/RoomProxy.swift#L272).

So, unfortunately for you, the HTML formatted value is the one expected and is correct regarding the Markdown standard.

It seems like Element Web is using a non-standard Markdown parser/version.

If one wants to get “newlines”/line-breaks in Markdown, the backslash must be used:

```
Wordle 793 4/6

⬛⬛🟨⬛⬛ \
🟨⬛⬛⬛⬛ \
🟩🟩⬛⬛⬛ \
🟩🟩🟩🟩🟩
```

will produce:

```
<p>Wordle 793 4/6</p>
<p>⬛⬛🟨⬛⬛ <br />
🟨⬛⬛⬛⬛ <br />
🟩🟩⬛⬛⬛ <br />
🟩🟩🟩🟩🟩</p>
```

which is what _you_ expect.

**Comment by Velin92** [comment] 2023-08-23 12:26
> So…
> 
> The following Markdown:
> 
> ```
> Wordle 793 4/6
> 
> ⬛⬛🟨⬛⬛
> 🟨⬛⬛⬛⬛
> 🟩🟩⬛⬛⬛
> 🟩🟩🟩🟩🟩
> ```
> 
> is compiled to the following HTML:
> 
> ```
> <p>Wordle 793 4/6</p>
> <p>⬛⬛🟨⬛⬛
> 🟨⬛⬛⬛⬛
> 🟩🟩⬛⬛⬛
> 🟩🟩🟩🟩🟩</p>
> ```
> 
> [See what Dingus says about it](https://spec.commonmark.org/dingus/?text=Wordle%20793%204%2F6%0A%0A%E2%AC%9B%E2%AC%9B%F0%9F%9F%A8%E2%AC%9B%E2%AC%9B%0A%F0%9F%9F%A8%E2%AC%9B%E2%AC%9B%E2%AC%9B%E2%AC%9B%0A%F0%9F%9F%A9%F0%9F%9F%A9%E2%AC%9B%E2%AC%9B%E2%AC%9B%0A%F0%9F%9F%A9%F0%9F%9F%A9%F0%9F%9F%A9%F0%9F%9F%A9%F0%9F%9F%A9).
> 
> And that's exactly what the Rust SDK provides.
> 
> All the messages Element X sends are formatted to Markdown, see [the sending part](https://github.com/vector-im/element-x-ios/blob/beeb5fc83c5af66fbea451afe61d2b8b40302d43/ElementX/Sources/Services/Room/RoomProxy.swift#L254), and the [formatting of the message](https://github.com/vector-im/element-x-ios/blob/beeb5fc83c5af66fbea451afe61d2b8b40302d43/ElementX/Sources/Services/Room/RoomProxy.swift#L272).
> 
> So, unfortunately for you, the HTML formatted value is the one expected and is correct regarding the Markdown standard.
> 
> It seems like Element Web is using a non-standard Markdown parser/version.
> 
> If one wants to get “newlines”/line-breaks in Markdown, the backslash must be used:
> 
> ```
> Wordle 793 4/6
> 
> ⬛⬛🟨⬛⬛ \
> 🟨⬛⬛⬛⬛ \
> 🟩🟩⬛⬛⬛ \
> 🟩🟩🟩🟩🟩
> ```
> 
> will produce:
> 
> ```
> <p>Wordle 793 4/6</p>
> <p>⬛⬛🟨⬛⬛ <br />
> 🟨⬛⬛⬛⬛ <br />
> 🟩🟩⬛⬛⬛ <br />
> 🟩🟩🟩🟩🟩</p>
> ```
> 
> which is what _you_ expect.
> 
> [See it in Dingus](https://spec.commonmark.org/dingus/?text=Wordle%20793%204%2F6%0A%0A%E2%AC%9B%E2%AC%9B%F0%9F%9F%A8%E2%AC%9B%E2%AC%9B%20%5C%0A%F0%9F%9F%A8%E2%AC%9B%E2%AC%9B%E2%AC%9B%E2%AC%9B%20%5C%0A%F0%9F%9F%A9%F0%9F%9F%A9%E2%AC%9B%E2%AC%9B%E2%AC%9B%20%5C%0A%F0%9F%9F%A9%F0%9F%9F%A9%F0%9F%9F%A9%F0%9F%9F%A9%F0%9F%9F%A9).

I see, so technically speaking we would either need to use a non standard markdown, like El-Web and also GitHub do.
However I think that when RTE is getting implemented all these issues will be already avoided client side, right? @aringenbach

**Comment by Hywan** [comment] 2023-08-23 12:33
Addition notes: line-breaks are considered as Hard line breaks in the spec, https://spec.commonmark.org/0.30/#hard-line-breaks. It works with more than 2 spaces at the end of the line etc.

Looking at the [GiHub Flavored Markdown spec](https://github.github.com/gfm/), there is no extension about line-breaks. However, if I test here, it works as _you_ expect. Anyway, it's not standard at all.

The Rust SDK uses Ruma to handle the Matrix types. Ruma uses [`pulldown-cmark`](https://github.com/raphlinus/pulldown-cmark/) to parse and compile Markdown. It is 100% compliant with CommonMark, and it does support some GitHub Flavored Markdown extensions, but not what you're looking for (as it's part of the GitHub spec…).

**Comment by Hywan** [comment] 2023-08-23 15:29
I'm going to unassign myself, and to remove the X-Needs-Rust tag here. Feel free to complain and I'll re-add this, but from my point of view, the Rust SDK is doing the _expected_ things: text is correctly parsed as Markdown, and correctly compiled to HTML.

The problem is the behavior we expect.

[The CommonMark specification about soft-breaks has this note](https://spec.commonmark.org/0.30/#soft-line-breaks):

> A renderer may also provide an option to render soft line breaks as hard line breaks.

Transforming a soft line breaks into a hard one is clearly not trivial. It depends on when we are in the AST: inside a list, code block, links, paragraph etc. I would not enter the marvelously terrible world of Markdown.

I join @Velin92 in believing it's an _editor_ problem. Whatever the solution we provide for soft line breaks, it will certainly break someone use case. Having a good editor (like [`matrix-rich-text-editor`](https://github.com/matrix-org/matrix-rich-text-editor)) is the solution to the problem.

**Comment by Hywan** [comment] 2023-08-24 07:41
I may have found an easy solution for that.

**Comment by Velin92** [comment] 2023-08-24 08:23
> I may have found an easy solution for that.

let's see if this is fixed by RTE first from @aringenbach , RTE is almost on its way to get merged.
Ofc if you think this may benefit the sdk go on, but maybe there higher priority things that require fixes there.

**Comment by Hywan** [comment] 2023-08-24 08:27
If https://github.com/ruma/ruma/pull/1636 is merged, it will fix the problem.

**Comment by Hywan** [comment] 2023-08-24 09:54
Problem solved.
The Rust SDK is updating to the latest ruma version in https://github.com/matrix-org/matrix-rust-sdk/pull/2452, but I'm already closing this issue :-).

**Closed by Hywan** 2023-08-24 09:54 UTC
Labels: X-Needs-Rust, A-Composer, T-Defect, S-Minor, O-Frequent, Z-Schedule, Z-Polish

**Comment by Hywan** [comment] 2023-08-24 09:56
@stefanceriu This is necessary to revert https://github.com/vector-im/element-x-ios/pull/1463 as soon as you update to the latest Rust SDK. Going to create a PR for that.

**Comment by Hywan** [comment] 2023-08-28 19:07
Build 366 contains the fix and it works like a charm. You can play your game now :-p.

**Comment by germain-gg** [comment] 2023-08-29 07:40
Thank you 🙌 

Wordle 801 4/6

🟨🟩⬛⬛⬛
⬛🟩🟨🟩⬛
🟨🟩🟨🟩🟩
🟩🟩🟩🟩🟩
