### ISSUE TITLE
History from before accepting an invite is not shown

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1170] opened 2023-06-26 21:20 UTC
### Steps to reproduce

1. Get invited to an e2ee room with scrollback
2. Accept invite on EI; read scrollback
3. Go to EX
4. Have to restart the app to get the new room visible in the roomlist
5. View new room
6. Observe scrollback from before you join the room is not visible

#### What did you expect?

scrollback prior to joining should be visible if history viz setting allows and sender sends keys for it (which it did)

#### What happened instead?

invisible history

### Application version

254

### Will you send logs?

Yes

**Comment by pixlwave** [comment] 2023-07-19 13:46
Duplicate of #1240.

**Closed by pixlwave** 2023-07-19 13:46 UTC
Labels: X-Needs-Rust, A-Timeline, T-Defect, A-E2EE, S-Critical, O-Frequent, Z-Schedule
