### ISSUE TITLE
Self-sent msgs mark rooms as unread

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#639] opened 2023-02-25 11:30 UTC
### Steps to reproduce

1. go into an unread room
2. send a message
3. go out; observe that the room is still marked as unread
4. go in again
5. go out again; observer thst the room is now marked as read

#### What did you expect?

reliable read state

### Application version

1.0.23 (42)

### Will you send logs?

No

**Comment by ara4n** [comment] 2023-03-25 17:23
Another aspect of this is that you can end up with a RM above your own last sent msg, like this, which feels super flakey:

![image](https://user-images.githubusercontent.com/1294269/227732234-0e7af684-2b84-4390-a0dd-14682929f797.jpeg)

**Comment by kittykat** [comment] 2023-07-05 09:56
Can't reproduce this in current TF, please reopen if you're still seeing it

**Comment by kittykat** [comment] 2023-07-12 12:07
I'm seeing this on today's TF

**Comment by ara4n** [comment] 2023-07-16 13:13
i still see this constantly.

**Comment by pixlwave** [comment] 2023-07-31 09:01
There's a little more to this than meets the eye. Sending a message doesn't mark the room as unread. However because EX currently only sends a read receipt on open/close of the room the issue can be reproduced as follows:
- Open a room (it will be marked as read).
- Wait for someone else to send a message (it will be marked as unread).
- Send a message (it remains unread, will investigate why).
- Close the room (it appears unread until the read receipt is sent).

**Closed** 2023-08-01 10:53 UTC
Labels: A-Room-List, T-Defect, S-Major, O-Occasional, Z-Schedule
