### ISSUE TITLE
Audio Messages

### ISSUE THREAD

**Issue by stefanceriu** [vector-im/element-x-ios#255] opened 2022-10-25 07:14 UTC
Build voice messages through mechanisms similar to Element

- \[ \] Download, decrypt and [convert](https://github.com/vector-im/swift-ogg)
- \[ \] Display and playback
- \[ \] Record and playback
- \[ \] Send

**Comment by kittykat** [comment] 2023-07-13 16:46
Duplicate of vector-im/internal-planning/issues/347

**Closed by kittykat** 2023-07-13 16:46 UTC
Labels: Z-BBQ-Beta, Team: ?
