### ISSUE TITLE
Element X unable to use https

### ISSUE THREAD

**Issue by p-fruck** [vector-im/element-x-ios#1978] opened 2023-10-29 14:53 UTC
### Steps to reproduce

Element X is unable to connect to our server using https. It should be noted that we use TLS 1.3 exclusively.

### Scenario 1
1. Point your matrix client to some webserver serving `.well-known/matrix/client` via https (http gets redirected to http)
1. Connect Element X using `https://your.server` as the server name

### Scenario 2
1. Point your matrix client to some webserver serving `.well-known/matrix/client` via https (http gets redirected to http)
2. Connect Element X using `http://your.server` as the server name

### Scenario 3
1. Point your matrix client to some webserver serving `.well-known/matrix/client` via http. Matrix homeserver and sync urls start with `https://`
2. Connect Element X using `http://your.server` as the server name

### Scenario 4
1. Point your matrix client to some webserver serving `.well-known/matrix/client` via http. Matrix homeserver and sync urls start with `http://`
2. Connect Element X using `http://your.server` as the server name

#### What did you expect?

Client should connect, request should be shown in server access log

##### Scenario 1

Client shows "server not supported", no request in access log

##### Scenario 2

Client shows "server not supported", request in access log (HTTP 301 redirect to HTTPS)

##### Scenario 3

Client detects server, shows that neither password login nor OIDC is supported (our server supports both)

##### Scenario 4

Client detects server, shows username/password prompt (no way to use OIDC). Login with username/password fails, likely because our server again redirects http to https

### Your phone model

Mac Mini M2 8C CPU, 10C GPU, 16 GB RAM, 512 GB SSD

### Application version

1.3.3

### Homeserver

Synapse 1.95

### Will you send logs?

No

**Comment by p-fruck** [comment] 2023-10-29 14:56
Oops, just noticed the error happens because of https://github.com/vector-im/element-x-ios/issues/786, sorry

**Comment by pixlwave** [comment] 2023-10-30 08:43
Closing as duplicate of #786.

**Closed by pixlwave** 2023-10-30 08:43 UTC
Labels: T-Defect
