### ISSUE TITLE
Plaintext msgs sent by RTE are unusably overescaped

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1665] opened 2023-09-09 10:30 UTC
### Steps to reproduce

1. Send a message like `!mjolnir ban`
2. get ignored by the bot
3. View source
4. See plaintext body is `\!mjolnir ban`

#### What did you expect?

plaintext body of rich text messages should be the plaintext the user entered; not some weird escaped markdown

#### What happened instead?

backslash escaping everywhere

### Application version

380

### Will you send logs?

No

**Comment by pixlwave** [comment] 2023-09-11 07:39
Duplicate of #1629

**Closed by pixlwave** 2023-09-11 07:39 UTC
