### ISSUE TITLE
Message preview shows Decryption error

### ISSUE THREAD

**Issue by germain-gg** [vector-im/element-x-ios#693] opened 2023-03-10 13:20 UTC
### Steps to reproduce

1. See a room in the room list with a message preview showing decryption error
2. Enter the room, see that the message is now decrypted
3. Go back to room list

#### What did you expect?

To see an updated message preview in the room list

#### What happened instead?

It still shows decryption error

### Will you send logs?

No

**Comment by kittykat** [comment] 2023-07-05 09:59
@germain-gg I can't reproduce this issue so will close it for now. Please reopen and send logs if you're still seeing it!

**Closed by kittykat** 2023-07-05 09:59 UTC
Labels: T-Defect, A-E2EE, S-Major, O-Occasional
