### ISSUE TITLE
Unsent messages are lost when switching away from a room

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1530] opened 2023-08-20 11:39 UTC
### Steps to reproduce

1. Send a message on bad data
2. Switch room before you get the remote echo
3. Go back to the room
4. Discover the message has been completely lost.

As a really simple demo, here’s an send failure on airplane mode getting lost - but it also happens when not on airplane mode and makes the app feel very unreliable if it silently drops sent msgs.

https://github.com/vector-im/element-x-ios/assets/1294269/cf9ccb51-9d98-4bdd-a0a6-cc0b6c76d9a7

#### What did you expect?

We should queue unsent and unsendable messages reliably

#### What happened instead?

They can get lost.

### Application version

345

### Will you send logs?

No

**Comment by pixlwave** [comment] 2023-08-23 17:54
Closing as duplicate of #517. I've copied the information from this report into that one.

**Closed by pixlwave** 2023-08-23 17:54 UTC
Labels: T-Defect
