### ISSUE TITLE
Pills are massive and ugly

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1872] opened 2023-10-09 23:58 UTC
### Steps to reproduce

1. View a message with a mention pill:

![image](https://github.com/vector-im/element-x-ios/assets/1294269/5c5f2666-95c8-434a-8d61-a6232fd533cb)

#### What did you expect?

Nice small pill shape which doesn’t distort the line spacing of the text, and whose avatar is aligned with equal spacing around the perimeter rather than uneven padding on the left side relative to the too & bottom

#### What happened instead?

A great big pill whose text is truncated (problem for raw mxids) and which distorts the line spacing of the message.

### Application version

405

### Will you send logs?

No

**Comment by stefanceriu** [comment] 2023-10-10 05:44
Duplicate of #1822

**Closed by stefanceriu** 2023-10-10 05:44 UTC

**Comment by manuroe** [comment] 2023-10-10 06:38
This is feature is still in development. We are making progress on the code side while the design is not yet ready.
